### ISSUE TITLE
Apti Rulers not getting migration events.

### ISSUE THREAD

**Issue by VectusPrime** [ThePinkPanzer/Godherja-Github-Version#362]
None of the Apti rulers are receiving the events that to allow them to migrate with the rest of the Imperrech cultures.

**Comment by VectusPrime** [comment]
Coming back to this a couple weeks later, joining the migration with an Apti ruler seems to work fine, the original issue may have had to do with backing out to the menu and starting new games, whereas playing after a fresh boot there is no issue.

**Comment by FedorBozic** [comment]
I'm leaving this open since I'm fairly sure what the cause is, and that it is indeed a bug (albeit not specific to the Apti). I'll escalate it into a high priority issue since this has been an irritant since forever. The actual issue is that characters in the Imperrech might randomly settle down before the player actually even leaves the lobby/picks a character, so from their perspective the Conquest will just straight up randomly not work.

**Comment by FedorBozic** [comment]
Fixed.
